Use new condor env format
opensciencegrid/BLAH pull request #73
Opened 2018-11-02 01:14 UTC by sthapa

A small patch to use new condor env format

2018-11-23 18:25 UTC, brianhlin commented
@edquist please make time to review this

2018-11-26 18:29 UTC, edquist commented on src/scripts/condor_submit.sh
> +              echo "12 -- ${fixed_env_var}" >> ~/foo
This looks like a debugging line that should be removed.

2018-11-26 18:44 UTC, edquist commented
What is the expected input format for the `-V` option? (that ends up in `$environment`)

Can it contain `'`'s or `"`'s?

BTW I notice in the usage string it mentions `[-v <environment>]`, instead of `-V`, which is the one this change deals with.  Not sure if this detail is relevant.

2018-11-26 18:58 UTC, edquist commented on src/scripts/condor_submit.sh
> +            submit_file_environment="environment = \" ${env_var}"
Probably minor, but is the space here between `\"` and `${env_var}"` intentional?  I'd guess no but it seems worth asking.

2018-11-26 19:01 UTC, edquist commented on src/scripts/condor_submit.sh
> +              submit_file_environment="${submit_file_environment} ${env_var} "
Does this handle the semicolons issue mentioned in the comment about `LS_COLORS`?

Seems like the escaping happens only when there are spaces.

2018-11-26 19:15 UTC, edquist commented
I've made a PR against @sthapa's branch with my suggested cleanups: https://github.com/sthapa/BLAH/pull/1

If i understand what's going on correctly, this should do the same thing, but maybe in a bit more straightforward way, and also handle semicolons, which as (i read the comments) was apparently the intention.

It does not try to handle embedded single-quotes (but neither does the original code).  If we want that, i suppose it'd just be an extra line to quote those too, but i don't know what the expected quoting rules are / how/where this variable gets used down the line.

2018-11-26 19:16 UTC, edquist requested changes
See comments.

Remove the debugging line at a minimum, and consider suggested cleanups.

2018-11-29 20:24 UTC, sthapa commented on src/scripts/condor_submit.sh
> +              echo "12 -- ${fixed_env_var}" >> ~/foo
Yeah, that is debugging output, can be removed

2018-11-29 20:24 UTC, sthapa commented on src/scripts/condor_submit.sh
> +            submit_file_environment="environment = \" ${env_var}"
I don't believe it is, but I don't think it hurts.

2018-11-29 20:26 UTC, sthapa commented on src/scripts/condor_submit.sh
> +              submit_file_environment="${submit_file_environment} ${env_var} "
Yes, it does.  The new condor env format doesn't use semicolons as delimiters.  The problem was the original env format used semicolons e.g. env=FOO=bar;TERM=xterm;OSG_SQUID=blah   .  With the new format spaces are delimiters so we need to escape them but that should be it.

2019-02-11 17:49 UTC, brianhlin commented
@edquist we don't have to address this in the 3.4.24 release of the blahp but let's get this done for the following version. Submit a new PR to opensciencegrid/blahp (either based off of this one or a completely new one)

2019-05-09 23:53 UTC, edquist commented
@sthapa, thanks for contributing this way back and I'm sorry for not getting it in sooner.  I did not really understand what the new condor env format was about at the time but after looking at the condor manual it makes sense to me now.  We'll get this PR merged in via #79 probably tomorrow with @brianhlin's approval.

2019-05-10 01:06 UTC, sthapa commented
No worries, I'm sure there's enough things happening that this might have been put on the backburner for a while.  Happy to contribute.

2019-05-10 19:20 UTC, closed without merging