Use the original proxy if blahp proxy delegation is disabled
opensciencegrid/BLAH pull request #76
Opened 2019-04-24 15:24 UTC by brianhlin

(SOFTWARE-3661)

Without this change, the blahp copies the job proxy into its own
working dir and uses that. Unfortunately, it seems like the blahp
relies on the BRPClient to pass along any proxy renewals, which
doesn't run when "blah_disable_wn_proxy_renewal=yes"

2019-04-24 15:27 UTC, brianhlin commented
@ptmcguigan here's a potential fix for the proxy refresh issue you're seeing.

@JaimeFrey does this look like a reasonable fix?

2019-04-24 18:57 UTC, JaimeFrey requested changes
I have two concerns about this patch:
* Using a relative path for the proxy filename won't work. (The gridmanager ensures a full path because the blahp used to not handle it. But the blahp does handle a relative path now and I'd rather not mess that up.)
* This won't work for PBS, LSF, or SGE configurations that use file transfer. (I believe OSG doesn't support such a configuration, but the blahp attempts to.)

Here's what I would do instead:
* Remove the added lines in bls_parse_submit_options().
* In bls_setup_all_files(), if bls_test_shared_dir() indicates the proxy file is shared (and bls_opt_proxyrenew=no), do the following:
  + Remove the existing bls_fl_add_value inputcopy ...
  + Don't set bls_need_to_reset_proxy=yes
  + Set bls_opt_proxy_string=$bls_proxy_local_file (thus giving us the full path)
* In bls_start_job_wrapper(), make the new else clause conditional on $bls_opt_proxy_string being non-empty.

2019-04-25 23:09 UTC, brianhlin commented
Ok @JaimeFrey, I think this simplifies the logic a bit:

- Just directly use `$bls_proxy_local_file` instead of changing the option value
- If the blahp is renewing the proxy, then we can use the proxy in its sandbox
- If the blahp is not renewing the proxy and the proxy lives in a shared dir, we can just use the original location
- However, if the blahp is not renewing the proxy and the proxy isn't in a shared dir, what we should do about the proxy is unclear. In the default OSG/HTCondor configs, the blahp assumes `/` is shared so this isn't a case we come across commonly.

2019-04-26 18:56 UTC, JaimeFrey requested changes
If the blahp isn't renewing the proxy and the proxy isn't in a shared directory, then the blahp should still attempt to transfer the proxy as an input file (i.e. invoke bls_fl_add_value inputsand ...). That way, the job gets the initial proxy, though it won't get any updates.

2019-04-26 19:42 UTC, brianhlin commented
@JaimeFrey that makes sense. Last iteration!

2019-04-26 21:33 UTC, JaimeFrey approved these changes
This iteration looks good.

2019-05-01 21:39 UTC, ptmcguigan commented
I put the proposed file into my test machine and tried to submit a job.  It didn't seem to work the way that I suspected that it should.  The resulting job in Torque would still have problems with the proxy.  I don't know if our blahp.  I don't know if you want to go into details on this thread or move it somewhere else.

2019-05-09 14:54 UTC, brianhlin commented
Whelp, turns out it was just a typo on my part and the latest version fixes it. @ptmcguigan I've dropped in the latest version on test06 and it works as expected (no `-W` and `X509_USER_CERT` set to `/cluster/grid/dev-spool/...`).

2019-05-09 14:58 UTC, JaimeFrey approved these changes
The latest fix looks good.

2019-05-09 15:00 UTC, merged